---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: development-app-svc   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  selector:
    app: development-app         # Map any pod with label `app=development-app` to this service
  ports:                         # Take incoming HTTP requests on 'port' and forward them to the 'targetPort'
  - name: TCP
    port: 31000
    targetPort: 8081