---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: development-app           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: development-latest        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this $
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: development-latest
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: docker-development-app
        image: yp29/jenkinsmultibranch:development-latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081  # Should match the port number that the node.js application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready to serve traffic or not
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    