---
apiVersion: extensions/v1beta1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: development-app           # Name of the Kubernetes resource
spec:
  replicas: 2                    # Number of pods to run at any given time
  template:
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: development-app
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: docker-development-app
        image: yp29/jenkinsmultibranch:development-base
        ports:
          - containerPort: 8081  # Should match the port number that the node.js application listens on