---
- hosts: deploy_k8s_servers
  become: yes
  become_method: sudo
  become_user: jenkins
  vars:
    terraform_version: "0.9.6"
  tasks:
    - name: Install Python
      apt: name=python-pip state=present
  
    - name: Install Docker
      pip: name=docker-py
      
    - name: Install Terraform
      gather_facts: False
      become: true
      roles:
        - { role: terraform }
    
    - name: Validate Terraform
      shell: terraform version